version: "3.9"

services:
  db:
    image: mysql:8-oracle
    restart: unless-stopped
    container_name: mlflow_db
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_new_volume:/var/lib/mysql
    networks:
      - internal

  mlflow:
    image: ubuntu/mlflow:2.1.1_1.0-22.04
    container_name: mlflow_tracker
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=../airflow/config/gcp_key_deb.json
    networks:
      - public
      - internal
    entrypoint: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root gs://${GCS_BUCKET_NAME}/ -h 0.0.0.0
    depends_on:
      wait-for-db:
        condition: service_completed_successfully

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:3306 -t 90s -i 250ms
    networks:
      - internal

  run_test_experiment:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    depends_on:
      - "mlflow"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=../airflow/config/gcp_key_deb.json
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    entrypoint: >
      /bin/sh -c "
      python3 mlflow_tracking.py;
      exit 0;
      "
    networks:
      - internal

networks:
  internal:
  public:
    driver: bridge
volumes:
  db_new_volume:
