FROM continuumio/miniconda3:latest

WORKDIR /app

# Update pip
RUN pip install -U pip

# Install MLflow requirements
COPY ./pipeline/mlflow/requirements.txt ./mlflow-requirements.txt
RUN pip install -r mlflow-requirements.txt

# Copy over the MLflow project
COPY ./pipeline/mlflow .
