apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: {{ .Values.airflow.scheduler.replicas }}
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler
        image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
        command: ["airflow", "scheduler"]
        env:
          {{- include "airflow.commonEnvVars" . | nindent 10 }}
        volumeMounts:
          {{- include "airflow.commonVolumeMounts" . | nindent 10 }}
      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs
        - name: config
          persistentVolumeClaim:
            claimName: airflow-config
        - name: plugins
          persistentVolumeClaim:
            claimName: airflow-plugins
        