apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgres.ports.internal }}
    targetPort: {{ .Values.postgres.ports.container }}
  selector:
    app: {{ .Values.postgres.name }}
