name: Upload Folder to Google Cloud Storage

on:
  push:
    branches:
      - main  # Set this to the branch that triggers the upload

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@v0.5.1
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true

    - name: Upload files to GCS
      run: |
        gsutil -m cp -r ./src/ gs://us-east1-airflow-orchestrat-9d0ee4bd-bucket/dags/
