name: Upload Code to Google Cloud Storage

on:
  push:
    branches:
      - main 
jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: Checkout Repo
      uses: actions/checkout@v3

    - id: 'auth'
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v2.1.2"
      with:
        credentials_json: "${{ secrets.GCS_SA_KEY }}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: firm-site-417617

    - name: 'Upload Source Code into DAGs'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'src/mlcore'
        destination: 'us-east1-airflow-orchestrat-9d0ee4bd-bucket/dags/'
